package com.iabtcf;

/**
 * @author evanwht1
 */
public enum Purpose {

	STORE_AND_ACCESS_INFO_ON_DEVICE(1),
	SELECT_BASIC_ADS(2),
	CREATE_PERSONALISED_ADS_PROFILE(3),
	SELECT_PERSONAL_ADS(4),
	CREATE_PERSONAL_CONTENT_PROFILE(5),
	SELECT_PERSONALISED_CONTENT(6),
	MEASURE_AD_PERFORMANCE(7),
	MEASURE_CONTENT_PERFORMANCE(8),
	APPLY_MARKET_RESEARCH_TO_GENERATE_AUDIENCE_INSIGHTS(9),
	DEVELOP_AND_IMPROVE_PRODUCTS(10),
	;

	private final int id;

	Purpose(final int id) {
		this.id = id;
	}

	public int getId() {
		return id;
	}
}
