# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java-maven/ for more details
#
version: 2
jobs:
  build:
    docker:
      # use this docker image
      # see https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/openjdk:8-jdk-stretch

    working_directory: ~/iabtcf-java

    steps:
      - checkout

      - run:
          name: Generate cumulative pom.xml checksum
          command: |
            find . -type f -name "pom.xml" -exec sh -c "sha256sum {} >> ~/.pom-checksum" \;
            sort -o ~/.pom-checksum ~/.pom-checksum
          when: always

      # Download and cache dependencies
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: iabtcf-java-{{ checksum "~/.pom-checksum" }}

      - run: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: iabtcf-java-{{ checksum "~/.pom-checksum" }}

      - run: mvn package

      - run:
          name: Save test results
          command: |
            mkdir -p ~/surefire-reports
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/surefire-reports \;
          when: always

      - store_test_results:
          # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: ~/surefire-reports

      - run:
          name: Save jars
          command: |
            mkdir -p ~/artifacts
            find . -type f -iname "*.jar" ! -name "*-tests.jar" -exec cp {} ~/artifacts \;
          when: always

      - store_artifacts:
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
          path: ~/artifacts
